name = "ScenarioTheory"
uuid = "34245d11-8d86-4cc3-9865-ee17c37bff99"
authors = ["Frederik Baymler Mathiesen <frederik@baymler.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
